---
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: module
  ecmaVersion: 11
plugins:
  - '@typescript-eslint'
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
ignorePatterns:
  - 'build/'
  - 'coverage/'
  - 'node_modules/'
  - 'public/'
rules:
  prettier/prettier:
    - error
    - endOfLine: lf
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/prefer-regexp-exec': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unsafe-assignment': warn
  '@typescript-eslint/no-unsafe-member-access': warn
  '@typescript-eslint/no-floating-promises': warn